pipeline {
    agent {
        node {
            label 'docker'
        }
    }

    stages {
        stage('Compile') {
            steps {
                sh 'gradle clean classes'
            }
        }

        stage('Test') {
            steps {
                sh 'gradle test'
            }
        }

        stage('Package') {
            steps {
                sh 'gradle build'
            }
        }
    }

}