pipeline {
    agent none

    stages {
        stage('Compile') {
            steps {
                sh './gradlew clean classes'
            }
        }

        stage('Test') {
            steps {
                sh './gradlew test'
            }
        }

        stage('Package') {
            steps {
                sh './gradlew build'
            }
        }
    }

}